site_name: Nadir Olabi Web Corner
site_description: Just a personal webpage for me (Muhammed Nadir olabi)

theme:
  name: material
  user_color_mode_toggle: true
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

  font:
    text: Noto Sans Mono
    code: Roboto Mono

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - content.code.copy
    - navigation.indexes
    # - navigation.path
    - navigation.prune
    # - header.autohide
    # - navigation.instant
    # - navigation.sections

markdown_extensions:
  # - admonition   # to be used with mkdocs special admonitions
  - pymdownx.arithmatex:
      generic: true
  - toc:
      title: TOC
      permalink: '#'
      toc_depth: '1-3'
  - nl2br
  - sane_lists
  - tables
  - attr_list
  - md_in_html

plugins:
  - search
  - tags:
      listings_map:
          custom-id:
              toc: false
  - blog:
      blog_dir: 6Things_Blog
      blog_toc: true
      archive: false
      post_date_format: full
      post_excerpt: required
      # post_excerpt_separator: <div dir="rtl" markdown="1">
  # - social
  # - gen-files:
  #     scripts:
  #         - gen_indexes.py

extra_javascript:
  # - javascript/mathjax.js  # for local use
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css





