site_name: Nadir Olabi Web Corner
site_description: Just a personal webpage for me (Muhammed Nadir olabi)

theme:
  user_color_mode_toggle: true
  name: material
  # palette:
  #   - scheme: default
  #     primary: indigo
  #     accent: indigo
  #     toggle:
  #       icon: material/weather-night
  #       name: Switch to dark mode
  #   - scheme: slate
  #     primary: green
  #     accent: light blue
  #     toggle:
  #       icon: material/weather-sunny
  #       name: Switch to light mode
  font:
    text: Noto Sans Mono
    code: Roboto Mono
  # name: mkdocs
  # name: null
  # custom_dir: 'styling_/terminal_theme/'
  # palette: dark
  # custom_dir: 'styling_/bootswatch_theme/darkly'
  # custom_dir: 'styling_/cinder'
  # colorscheme: dracula
  features:
    # - navigation.path
    # - navigation.prune
    - navigation.tabs
    # - header.autohide
    - navigation.top
    - content.code.copy
    # - navigation.indexes
    # - navigation.instant
    # - navigation.sections


markdown_extensions:
  # - admonition   # to be used with mkdocs special admonitions
  - pymdownx.arithmatex:
      generic: true
  - toc:
      title: TOC
      permalink: '#'
      toc_depth: '1-3'
  - nl2br
  - sane_lists
  - tables
  - attr_list
  - md_in_html

plugins:
  - search
  - tags:
      listings_map:
          custom-id:
              toc: false
  # - blog
  # - social

extra_javascript:
  # - javascript/mathjax.js  # for local use
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css





