site_name: Nadir Olabi Web Corner
site_description: Just a personal webpage for me (Muhammed Nadir olabi)

theme:
  user_color_mode_toggle: true
  name: material
  # palette:
  #   scheme: slate
  #   primary: green
  #   accent: light blue
  font:
    text: Noto Sans Mono
    code: Roboto Mono
  # name: mkdocs
  # name: null
  # custom_dir: 'styling_/terminal_theme/'
  # palette: dark
  # custom_dir: 'styling_/bootswatch_theme/darkly'
  # custom_dir: 'styling_/cinder'
  # colorscheme: dracula
  features:
    # - header.autohide

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: '#'
      toc_depth: '1-3'
  - nl2br
  - sane_lists
  - tables
  - attr_list
  - md_in_html

plugins:
  - search
  - tags
  # - blog
  # - social

extra_javascript:
  # - javascript/mathjax.js  # for local use
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css





